name: React Auto Deploy

on:
  push:
    branches:
      - master  # Master branch'e her push'ta Ã§alÄ±ÅŸacak

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸš€ Repoâ€™yu Kopyala
        uses: actions/checkout@v3

      - name: ðŸ”‘ VPSâ€™e SSH ile BaÄŸlan ve Deploy Scriptâ€™i Ã‡alÄ±ÅŸtÄ±r
        run: |
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key serkanursavas@147.93.126.10 -p 2222 "cd /home/serkanursavas/projects/react && ./deploy.sh"

